// Generated by Cursor

package main

import (
	"bufio"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/vmware/govmomi"
	"github.com/vmware/govmomi/find"
	"github.com/vmware/govmomi/object"
	"github.com/vmware/govmomi/vim25/mo"
	"github.com/vmware/govmomi/vim25/types"
)

type arrayFlags []string

func (a *arrayFlags) String() string {
	return strings.Join(*a, ", ")
}

func (a *arrayFlags) Set(value string) error {
	*a = append(*a, value)
	return nil
}

type ForkliftLogEntry struct {
	Level  string                 `json:"level"`
	Ts     string                 `json:"ts"`
	Logger string                 `json:"logger"`
	Msg    string                 `json:"msg"`
	Fields map[string]interface{} `json:"-"`
}

func (f *ForkliftLogEntry) UnmarshalJSON(data []byte) error {
	type Alias ForkliftLogEntry
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(f),
	}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal into map to get all fields
	var allFields map[string]interface{}
	if err := json.Unmarshal(data, &allFields); err != nil {
		return err
	}
	f.Fields = allFields
	return nil
}

var logOutput = struct {
	sync.Mutex
	writer *log.Logger
}{
	writer: log.New(os.Stdout, "", 0),
}

// Track completed snapshot removal tasks to detect lingering snapshots
type completedRemoval struct {
	snapshotName   string
	completionTime time.Time
	reported       bool
}

var (
	pendingRemovals   = make(map[string]*completedRemoval) // task key -> removal info
	pendingRemovalsMu sync.Mutex
)

func logPrint(format string, args ...interface{}) {
	logOutput.Lock()
	defer logOutput.Unlock()
	logOutput.writer.Printf(format, args...)
}

func main() {
	var (
		vcURL            = flag.String("url", "", "vCenter URL (https://user:pass@vcenter/sdk)")
		vmName           = flag.String("vm", "", "VM name to monitor")
		diskPaths        arrayFlags
		interval         = flag.Int("interval", 2, "Poll interval in seconds")
		insecure         = flag.Bool("insecure", false, "Skip TLS verification")
		namespace        = flag.String("namespace", "", "Kubernetes namespace for forklift-controller (optional)")
		planName         = flag.String("plan", "", "Plan name to watch in forklift logs (optional, requires -namespace)")
		controllerPod    = flag.String("controller-pod", "", "Specific forklift-controller pod name (optional, auto-detected if not provided)")
		watchDVs         = flag.Bool("watch-dvs", false, "Watch DataVolumes for duplicate checkpoints (requires -namespace and -plan)")
		lingerDelay      = flag.Int("linger-delay", 10, "Seconds to wait after RemoveSnapshot success before checking if snapshot lingers")
	)
	flag.Var(&diskPaths, "disk", "Disk path to watch for (e.g., '[datastore] vm/disk.vmdk'). Can be specified multiple times.")
	flag.Parse()

	if *vcURL == "" || *vmName == "" || len(diskPaths) == 0 {
		flag.Usage()
		log.Fatal("Required flags: -url, -vm, -disk (at least one)")
	}

	if *planName != "" && *namespace == "" {
		log.Fatal("Error: -plan requires -namespace")
	}

	if *watchDVs && (*namespace == "" || *planName == "") {
		log.Fatal("Error: -watch-dvs requires both -namespace and -plan")
	}

	ctx := context.Background()

	// Parse URL
	u, err := url.Parse(*vcURL)
	if err != nil {
		log.Fatal(err)
	}

	// Connect to vCenter
	client, err := govmomi.NewClient(ctx, u, *insecure)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Logout(ctx)

	log.Printf("Connected to vCenter: %s\n", u.Host)

	// Find datacenter
	finder := find.NewFinder(client.Client, true)
	dc, err := finder.DefaultDatacenter(ctx)
	if err != nil {
		log.Fatal(err)
	}
	finder.SetDatacenter(dc)
	log.Printf("Using datacenter: %s\n", dc.Name())

	// Find VM
	vm, err := finder.VirtualMachine(ctx, *vmName)
	if err != nil {
		log.Fatal(err)
	}

	logPrint("Monitoring VM: %s\n", *vmName)
	logPrint("Watching for disk(s):\n")
	for _, disk := range diskPaths {
		logPrint("  - %s\n", disk)
	}
	logPrint("Poll interval: %d seconds\n", *interval)
	logPrint("Snapshot linger detection delay: %d seconds\n", *lingerDelay)
	if *namespace != "" {
		logPrint("Monitoring forklift-controller in namespace: %s\n", *namespace)
		if *planName != "" {
			logPrint("Filtering for plan: %s\n", *planName)
		}
		if *watchDVs {
			logPrint("Watching DataVolumes for duplicate checkpoints\n")
		}
	}
	logPrint("=====================================\n")

	// Start forklift log monitoring if requested
	if *namespace != "" {
		go monitorForkliftLogs(ctx, *namespace, *controllerPod, *planName)
	}

	// Start DataVolume monitoring if requested
	if *watchDVs {
		go monitorDataVolumes(ctx, *namespace, *planName)
	}

	// Track state changes
	var lastPowerState types.VirtualMachinePowerState
	var lastSnapshotCount int
	lastDiskPresence := make(map[string]bool)
	seenTasks := make(map[string]bool) // Track tasks we've already reported

	ticker := time.NewTicker(time.Duration(*interval) * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		timestamp := time.Now().Format("15:04:05.000")

		// Check if session is still active, reconnect if needed
		sessionActive, err := client.SessionManager.SessionIsActive(ctx)
		if err != nil || !sessionActive {
			logPrint("[%s] Session expired, reconnecting...\n", timestamp)
			client.Logout(ctx)
			client, err = govmomi.NewClient(ctx, u, *insecure)
			if err != nil {
				logPrint("[%s] ERROR reconnecting to vCenter: %v\n", timestamp, err)
				time.Sleep(5 * time.Second)
				continue
			}
			logPrint("[%s] Successfully reconnected to vCenter\n", timestamp)

			// Re-find the VM
			finder = find.NewFinder(client.Client, true)
			dc, err = finder.DefaultDatacenter(ctx)
			if err != nil {
				logPrint("[%s] ERROR finding datacenter: %v\n", timestamp, err)
				continue
			}
			finder.SetDatacenter(dc)
			vm, err = finder.VirtualMachine(ctx, *vmName)
			if err != nil {
				logPrint("[%s] ERROR finding VM: %v\n", timestamp, err)
				continue
			}
		}

		// Get VM properties including full snapshot details
		var vmObj mo.VirtualMachine
		err = vm.Properties(ctx, vm.Reference(), []string{
			"runtime.powerState",
			"config.hardware.device",
			"snapshot",
			"snapshot.rootSnapshotList",
			"recentTask",
		}, &vmObj)
		if err != nil {
			logPrint("[%s] ERROR querying VM: %v\n", timestamp, err)
			continue
		}

		// Check for recent snapshot-related tasks
		if len(vmObj.RecentTask) > 0 {
			checkVMTasks(ctx, client, vmObj.RecentTask, seenTasks, timestamp)
		}

		// Check for lingering snapshots (snapshots that remain after removal task completed)
		checkLingeringSnapshots(vmObj.Snapshot, *lingerDelay, timestamp)

		// Check power state changes
		if vmObj.Runtime.PowerState != lastPowerState {
			logPrint("[%s] *** POWER STATE CHANGED: %s -> %s ***\n",
				timestamp, lastPowerState, vmObj.Runtime.PowerState)
			lastPowerState = vmObj.Runtime.PowerState
		}

		// Find disks in hardware config and check for snapshot chain issues
		disksInConfig := make(map[string]bool)
		disksWithEmptyParent := []string{}
		disksInSnapshots := make(map[string]bool)

		for _, device := range vmObj.Config.Hardware.Device {
			if disk, ok := device.(*types.VirtualDisk); ok {
				fileName := getDiskFileName(disk)
				disksInConfig[fileName] = true

				// Check if this disk has a snapshot backing but no parent
				if hasEmptyParent(disk) {
					disksWithEmptyParent = append(disksWithEmptyParent, fileName)
				}

				// Walk the backing chain to find parent disks (simulates CDI's snapshot lookup)
				walkBackingChain(disk, disksInSnapshots)
			}
		}

		// Report disks with snapshot backing but no parent
		if len(disksWithEmptyParent) > 0 {
			logPrint("[%s] ⚠️  DISKS WITH SNAPSHOT BACKING BUT NO PARENT: %v\n", timestamp, disksWithEmptyParent)
		}

		// Count snapshots
		snapshotCount := 0
		var snapshotNames []string
		if vmObj.Snapshot != nil {
			snapshotCount = countSnapshots(vmObj.Snapshot.RootSnapshotList)
			snapshotNames = getSnapshotNames(vmObj.Snapshot.RootSnapshotList)
		}

		// Check snapshot count changes
		if snapshotCount != lastSnapshotCount {
			logPrint("[%s] *** SNAPSHOT COUNT CHANGED: %d -> %d ***\n",
				timestamp, lastSnapshotCount, snapshotCount)
			if snapshotCount > 0 {
				logPrint("[%s]     Snapshots: %v\n", timestamp, snapshotNames)
			}
			lastSnapshotCount = snapshotCount
		}

		// Check all target disks (in hardware config OR snapshots, like CDI does)
		diskStatuses := make([]string, 0, len(diskPaths))
		anyNotFound := false

		for _, diskPath := range diskPaths {
			targetDiskInConfig := disksInConfig[diskPath]
			targetDiskInSnapshot := disksInSnapshots[diskPath]
			targetDiskFound := targetDiskInConfig || targetDiskInSnapshot

			// Report changes in disk presence
			if lastPresent, exists := lastDiskPresence[diskPath]; exists && lastPresent != targetDiskFound {
				if targetDiskFound {
					logPrint("[%s] ✓✓✓ DISK APPEARED: %s ✓✓✓\n", timestamp, diskPath)
				} else {
					logPrint("[%s] ✗✗✗ DISK DISAPPEARED: %s ✗✗✗\n", timestamp, diskPath)
				}
			}
			lastDiskPresence[diskPath] = targetDiskFound

			// Build status string for this disk
			status := "✓"
			if !targetDiskFound {
				status = "✗"
				anyNotFound = true
			}
			diskStatuses = append(diskStatuses, status)
		}

		// Periodic status
		logPrint("[%s] PowerState=%s Snapshots=%d Disks=%v TotalDisksInConfig=%d TotalDisksInSnapshots=%d\n",
			timestamp,
			vmObj.Runtime.PowerState,
			snapshotCount,
			diskStatuses,
			len(disksInConfig),
			len(disksInSnapshots))

		// If any target disk is not found anywhere (like CDI would fail), list what we DID find
		if anyNotFound {
			logPrint("[%s] ✗✗✗ WARNING: Some disks NOT FOUND (CDI would fail!) ✗✗✗\n", timestamp)
			for _, diskPath := range diskPaths {
				targetDiskInConfig := disksInConfig[diskPath]
				targetDiskInSnapshot := disksInSnapshots[diskPath]
				targetDiskFound := targetDiskInConfig || targetDiskInSnapshot
				if !targetDiskFound {
					logPrint("[%s]   Missing: %s (InConfig=%v InSnapshot=%v)\n", timestamp, diskPath, targetDiskInConfig, targetDiskInSnapshot)
				} else {
					logPrint("[%s]   Found: %s\n", timestamp, diskPath)
				}
			}
			logPrint("[%s] Disks in Hardware Config:\n", timestamp)
			if len(disksInConfig) > 0 {
				for disk := range disksInConfig {
					logPrint("    - %s\n", disk)
				}
			} else {
				logPrint("    (none)\n")
			}
			logPrint("[%s] Disks in Snapshot Tree:\n", timestamp)
			if len(disksInSnapshots) > 0 {
				for disk := range disksInSnapshots {
					logPrint("    - %s\n", disk)
				}
			} else {
				logPrint("    (none)\n")
			}
		}
	}
}

func getDiskFileName(disk *types.VirtualDisk) string {
	device := disk.GetVirtualDevice()
	if backing, ok := device.Backing.(types.BaseVirtualDeviceFileBackingInfo); ok {
		info := backing.GetVirtualDeviceFileBackingInfo()
		return info.FileName
	}
	return ""
}

func countSnapshots(snapshots []types.VirtualMachineSnapshotTree) int {
	count := len(snapshots)
	for _, snap := range snapshots {
		count += countSnapshots(snap.ChildSnapshotList)
	}
	return count
}

func getSnapshotNames(snapshots []types.VirtualMachineSnapshotTree) []string {
	var names []string
	for _, snap := range snapshots {
		names = append(names, snap.Name)
		names = append(names, getSnapshotNames(snap.ChildSnapshotList)...)
	}
	return names
}

func hasEmptyParent(disk *types.VirtualDisk) bool {
	device := disk.GetVirtualDevice()

	// Check if this is a FlatVer2 backing (most common)
	if backing, ok := device.Backing.(*types.VirtualDiskFlatVer2BackingInfo); ok {
		// If the disk name looks like a snapshot (contains -00000X), check for parent
		fileName := backing.FileName
		if isSnapshotDisk(fileName) && backing.Parent == nil {
			return true
		}
	}

	// Check if this is a SparseVer2 backing
	if backing, ok := device.Backing.(*types.VirtualDiskSparseVer2BackingInfo); ok {
		fileName := backing.FileName
		if isSnapshotDisk(fileName) && backing.Parent == nil {
			return true
		}
	}

	return false
}

func isSnapshotDisk(fileName string) bool {
	// Snapshot disks typically have names like: disk-000001.vmdk, disk-000002.vmdk, etc.
	// Check if filename contains pattern like -000001 through -999999
	for i := 0; i < len(fileName)-7; i++ {
		if fileName[i] == '-' &&
			fileName[i+1] >= '0' && fileName[i+1] <= '9' &&
			fileName[i+2] >= '0' && fileName[i+2] <= '9' &&
			fileName[i+3] >= '0' && fileName[i+3] <= '9' &&
			fileName[i+4] >= '0' && fileName[i+4] <= '9' &&
			fileName[i+5] >= '0' && fileName[i+5] <= '9' &&
			fileName[i+6] >= '0' && fileName[i+6] <= '9' {
			return true
		}
	}
	return false
}

func checkVMTasks(ctx context.Context, client *govmomi.Client, taskRefs []types.ManagedObjectReference, seenTasks map[string]bool, timestamp string) {
	for _, taskRef := range taskRefs {
		taskKey := taskRef.Value

		// Get task details
		task := object.NewTask(client.Client, taskRef)
		var taskInfo mo.Task
		err := task.Properties(ctx, task.Reference(), []string{"info"}, &taskInfo)
		if err != nil {
			continue
		}

		info := taskInfo.Info

		// Filter for snapshot-related tasks
		isSnapshotTask := false
		isRemoveSnapshot := false
		var taskDesc string

		switch info.DescriptionId {
		case "VirtualMachine.removeSnapshot", "vm.Snapshot.remove", "VirtualMachine.removeSnapshot_Task":
			taskDesc = "🗑️  [VMWARE] RemoveSnapshot"
			isSnapshotTask = true
			isRemoveSnapshot = true
		case "VirtualMachine.createSnapshot", "VirtualMachine.createSnapshot_Task":
			taskDesc = "📸 [VMWARE] CreateSnapshot"
			isSnapshotTask = true
		case "VirtualMachine.removeAllSnapshots":
			taskDesc = "🗑️  [VMWARE] RemoveAllSnapshots"
			isSnapshotTask = true
			isRemoveSnapshot = true
		case "VirtualMachine.consolidateDisks":
			taskDesc = "🔄 [VMWARE] ConsolidateDisks"
			isSnapshotTask = true
		}

		if !isSnapshotTask {
			continue
		}

		// Check if we've already reported this task
		alreadySeen := seenTasks[taskKey]

		// Get task timestamp
		var taskTime time.Time
		if info.StartTime != nil {
			taskTime = *info.StartTime
		} else if !info.QueueTime.IsZero() {
			taskTime = info.QueueTime
		} else {
			taskTime = time.Now()
		}
		taskTimestamp := taskTime.Format("15:04:05.000")

		// Try to extract snapshot name from various sources
		snapshotName := extractSnapshotName(info)

		// Build status message
		status := ""
		shouldReport := false
		switch info.State {
		case types.TaskInfoStateQueued:
			status = "queued"
			shouldReport = !alreadySeen
		case types.TaskInfoStateRunning:
			status = "running"
			shouldReport = !alreadySeen
		case types.TaskInfoStateSuccess:
			status = "✓ success"
			shouldReport = !alreadySeen
			if shouldReport {
				seenTasks[taskKey] = true // Mark as seen once completed

				// Track successful RemoveSnapshot for lingering detection
				if isRemoveSnapshot && snapshotName != "" {
					pendingRemovalsMu.Lock()
					pendingRemovals[snapshotName] = &completedRemoval{
						snapshotName:   snapshotName,
						completionTime: time.Now(),
						reported:       false,
					}
					pendingRemovalsMu.Unlock()
					logPrint("[%s] 👁️  Tracking snapshot '%s' for lingering detection\n", timestamp, snapshotName)
				}
			}
		case types.TaskInfoStateError:
			status = "✗ error"
			shouldReport = !alreadySeen
			if shouldReport {
				seenTasks[taskKey] = true
			}
		}

		if !shouldReport {
			continue
		}

		if snapshotName != "" {
			logPrint("[%s] %s (%s) - %s\n", taskTimestamp, taskDesc, status, snapshotName)
		} else {
			logPrint("[%s] %s (%s)\n", taskTimestamp, taskDesc, status)
		}
	}
}

// extractSnapshotName tries to extract the snapshot name from task info
func extractSnapshotName(info types.TaskInfo) string {
	// Try description message
	if info.Description != nil && len(info.Description.Message) > 0 {
		return info.Description.Message
	}

	// Try to get from entity name if it's a snapshot
	if info.EntityName != "" {
		return info.EntityName
	}

	// Try to extract from description ID arguments (if available)
	// The task entity might be the snapshot itself
	if info.Entity != nil && info.Entity.Type == "VirtualMachineSnapshot" {
		// The Value often contains useful info
		return info.Entity.Value
	}

	return ""
}

// checkLingeringSnapshots checks if any snapshots that should have been removed are still present
func checkLingeringSnapshots(snapshotInfo *types.VirtualMachineSnapshotInfo, lingerDelaySec int, timestamp string) {
	if snapshotInfo == nil {
		// No snapshots - clear any pending removals that are old enough (they succeeded)
		pendingRemovalsMu.Lock()
		defer pendingRemovalsMu.Unlock()
		now := time.Now()
		for name, removal := range pendingRemovals {
			if now.Sub(removal.completionTime) > time.Duration(lingerDelaySec)*time.Second && !removal.reported {
				logPrint("[%s] ✅ Snapshot '%s' successfully removed (verified after %ds)\n",
					timestamp, name, lingerDelaySec)
				delete(pendingRemovals, name)
			}
		}
		return
	}

	// Get current snapshot names
	currentSnapshots := make(map[string]bool)
	collectSnapshotNames(snapshotInfo.RootSnapshotList, currentSnapshots)

	pendingRemovalsMu.Lock()
	defer pendingRemovalsMu.Unlock()

	now := time.Now()
	for name, removal := range pendingRemovals {
		elapsed := now.Sub(removal.completionTime)

		// Only check after the delay has passed
		if elapsed < time.Duration(lingerDelaySec)*time.Second {
			continue
		}

		if currentSnapshots[name] {
			// Snapshot is still present after removal task completed!
			if !removal.reported {
				logPrint("[%s] ⚠️⚠️⚠️  LINGERING SNAPSHOT DETECTED: '%s' still exists %v after RemoveSnapshot success! ⚠️⚠️⚠️\n",
					timestamp, name, elapsed.Round(time.Second))
				removal.reported = true
			}
		} else {
			// Snapshot was removed successfully
			if !removal.reported {
				logPrint("[%s] ✅ Snapshot '%s' successfully removed (verified after %v)\n",
					timestamp, name, elapsed.Round(time.Second))
			}
			delete(pendingRemovals, name)
		}
	}
}

// collectSnapshotNames recursively collects all snapshot names
func collectSnapshotNames(snapshots []types.VirtualMachineSnapshotTree, names map[string]bool) {
	for _, snap := range snapshots {
		names[snap.Name] = true
		collectSnapshotNames(snap.ChildSnapshotList, names)
	}
}

func walkBackingChain(disk *types.VirtualDisk, disks map[string]bool) {
	device := disk.GetVirtualDevice()

	// Handle FlatVer2 backing (most common)
	if backing, ok := device.Backing.(*types.VirtualDiskFlatVer2BackingInfo); ok {
		// Add current disk
		if backing.FileName != "" {
			disks[backing.FileName] = true
		}
		// Walk parent chain
		parent := backing.Parent
		for parent != nil {
			if parent.FileName != "" {
				disks[parent.FileName] = true
			}
			parent = parent.Parent
		}
	}

	// Handle SparseVer2 backing
	if backing, ok := device.Backing.(*types.VirtualDiskSparseVer2BackingInfo); ok {
		if backing.FileName != "" {
			disks[backing.FileName] = true
		}
		parent := backing.Parent
		for parent != nil {
			if parent.FileName != "" {
				disks[parent.FileName] = true
			}
			parent = parent.Parent
		}
	}
}

func monitorDataVolumes(ctx context.Context, namespace, planName string) {
	// Track checkpoints and phase for each DataVolume
	dvCheckpoints := make(map[string][]string) // DV name -> list of checkpoint "current" values
	dvPhases := make(map[string]string)        // DV name -> last known phase

	// Get the Plan UID and target namespace - DataVolumes are created in the target namespace, not the plan namespace
	planCmd := exec.CommandContext(ctx, "kubectl", "get", "plans.forklift.konveyor.io", "-n", namespace,
		planName, "-o", "jsonpath={.metadata.uid},{.spec.targetNamespace}")
	planOutput, err := planCmd.Output()
	if err != nil {
		logPrint("[DV-MONITOR] ERROR: Failed to get plan info for plan '%s': %v\n", planName, err)
		return
	}
	parts := strings.Split(strings.TrimSpace(string(planOutput)), ",")
	if len(parts) != 2 {
		logPrint("[DV-MONITOR] ERROR: Failed to parse plan info for '%s'\n", planName)
		return
	}
	planUID := parts[0]
	targetNamespace := parts[1]

	if planUID == "" {
		logPrint("[DV-MONITOR] ERROR: Plan '%s' not found in namespace %s\n", planName, namespace)
		return
	}
	if targetNamespace == "" {
		logPrint("[DV-MONITOR] ERROR: Plan '%s' has no target namespace\n", planName)
		return
	}
	logPrint("[DV-MONITOR] Monitoring DataVolumes for plan %s (UID: %s) in target namespace: %s\n", planName, planUID, targetNamespace)

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	lastStatusReport := time.Now()

	for range ticker.C {
		timestamp := time.Now().Format("15:04:05.000")

		// Get DataVolumes for this plan using the plan UID in the target namespace
		cmd := exec.CommandContext(ctx, "kubectl", "get", "datavolumes", "-n", targetNamespace,
			"-l", fmt.Sprintf("plan=%s", planUID),
			"-o", "json")
		output, err := cmd.Output()
		if err != nil {
			// Log error occasionally but don't spam
			continue
		}

		// Parse JSON output
		var result struct {
			Items []struct {
				Metadata struct {
					Name string `json:"name"`
				} `json:"metadata"`
				Spec struct {
					Checkpoints     []map[string]interface{} `json:"checkpoints"`
					FinalCheckpoint bool                     `json:"finalCheckpoint"`
				} `json:"spec"`
				Status struct {
					Phase    string `json:"phase"`
					Progress string `json:"progress"`
				} `json:"status"`
			} `json:"items"`
		}

		if err := json.Unmarshal(output, &result); err != nil {
			continue
		}

		// Periodic status report
		if time.Since(lastStatusReport) > 30*time.Second {
			logPrint("[%s] [DV-MONITOR] Tracking %d DataVolume(s)\n", timestamp, len(result.Items))
			lastStatusReport = time.Now()
		}

		// Check each DataVolume for checkpoint and phase changes
		for _, dv := range result.Items {
			dvName := dv.Metadata.Name
			currentPhase := dv.Status.Phase

			// Check for phase changes
			if lastPhase, exists := dvPhases[dvName]; exists {
				if lastPhase != currentPhase {
					progressStr := ""
					if dv.Status.Progress != "" {
						progressStr = fmt.Sprintf(" (progress: %s)", dv.Status.Progress)
					}
					logPrint("[%s] [DV:%s] 🔄 Phase: %s -> %s%s\n",
						timestamp, dvName, lastPhase, currentPhase, progressStr)
				}
			} else {
				// First time seeing this DataVolume, log its current state
				progressStr := ""
				if dv.Status.Progress != "" {
					progressStr = fmt.Sprintf(" (progress: %s)", dv.Status.Progress)
				}
				logPrint("[%s] [DV:%s] ℹ️  Initial phase: %s%s (checkpoints: %d)\n",
					timestamp, dvName, currentPhase, progressStr, len(dv.Spec.Checkpoints))
			}
			dvPhases[dvName] = currentPhase

			// Extract current checkpoint values
			var currentCheckpoints []string
			for _, cp := range dv.Spec.Checkpoints {
				if current, ok := cp["current"].(string); ok && current != "" {
					currentCheckpoints = append(currentCheckpoints, current)
				}
			}

			// Check for duplicates in the checkpoint list
			seen := make(map[string]bool)
			var duplicates []string
			for _, cp := range currentCheckpoints {
				if seen[cp] {
					duplicates = append(duplicates, cp)
				}
				seen[cp] = true
			}

			if len(duplicates) > 0 {
				logPrint("[%s] [DV:%s] ⚠️  DUPLICATE CHECKPOINTS DETECTED: %v\n", timestamp, dvName, duplicates)
			}

			// Check if checkpoints were added
			oldCheckpoints := dvCheckpoints[dvName]
			if len(currentCheckpoints) > len(oldCheckpoints) {
				// Find new checkpoints
				oldSet := make(map[string]bool)
				for _, cp := range oldCheckpoints {
					oldSet[cp] = true
				}
				var newCheckpoints []string
				for _, cp := range currentCheckpoints {
					if !oldSet[cp] {
						newCheckpoints = append(newCheckpoints, cp)
					}
				}
				if len(newCheckpoints) > 0 {
					finalStr := ""
					if dv.Spec.FinalCheckpoint {
						finalStr = " (FINAL)"
					}
					logPrint("[%s] [DV:%s] 📸 Checkpoint added: %v%s (total: %d)\n",
						timestamp, dvName, newCheckpoints, finalStr, len(currentCheckpoints))
				}
			}

			// Update tracked checkpoints
			dvCheckpoints[dvName] = currentCheckpoints
		}
	}
}

func monitorForkliftLogs(ctx context.Context, namespace, podName, planName string) {
	// Auto-detect pod if not specified
	if podName == "" {
		// Try multiple methods to find the forklift-controller pod
		labelSelectors := []string{
			"app=forklift-controller",
			"control-plane=controller-manager",
			"app.kubernetes.io/name=forklift-controller",
		}

		for _, label := range labelSelectors {
			cmd := exec.CommandContext(ctx, "kubectl", "get", "pods", "-n", namespace,
				"-l", label, "-o", "jsonpath={.items[0].metadata.name}")
			output, err := cmd.Output()
			if err == nil && strings.TrimSpace(string(output)) != "" {
				podName = strings.TrimSpace(string(output))
				break
			}
		}

		// If still not found, try searching by name pattern
		if podName == "" {
			cmd := exec.CommandContext(ctx, "kubectl", "get", "pods", "-n", namespace,
				"-o", "jsonpath={.items[?(@.metadata.name matches 'forklift-controller-.*')].metadata.name}")
			output, err := cmd.Output()
			if err == nil && strings.TrimSpace(string(output)) != "" {
				podName = strings.TrimSpace(string(output))
			}
		}

		// Last resort: just get all pods and grep for forklift-controller
		if podName == "" {
			cmd := exec.CommandContext(ctx, "kubectl", "get", "pods", "-n", namespace,
				"-o", "name")
			output, err := cmd.Output()
			if err != nil {
				logPrint("[FORKLIFT] ERROR: Failed to list pods: %v\n", err)
				return
			}
			lines := strings.Split(string(output), "\n")
			for _, line := range lines {
				if strings.Contains(line, "forklift-controller") {
					podName = strings.TrimPrefix(line, "pod/")
					break
				}
			}
		}

		if podName == "" {
			logPrint("[FORKLIFT] ERROR: No forklift-controller pod found in namespace %s\n", namespace)
			logPrint("[FORKLIFT] Try specifying the pod name with -controller-pod\n")
			return
		}
		logPrint("[FORKLIFT] Monitoring pod: %s\n", podName)
	}

	// Tail the logs
	cmd := exec.CommandContext(ctx, "kubectl", "logs", "-n", namespace, podName, "-f", "--tail=0", "-c", "main")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		logPrint("[FORKLIFT] ERROR: Failed to create stdout pipe: %v\n", err)
		return
	}

	if err := cmd.Start(); err != nil {
		logPrint("[FORKLIFT] ERROR: Failed to start kubectl logs: %v\n", err)
		return
	}

	scanner := bufio.NewScanner(stdout)
	// Increase buffer size for very long log lines (default is 64KB, set to 1MB)
	const maxScanTokenSize = 1024 * 1024
	buf := make([]byte, maxScanTokenSize)
	scanner.Buffer(buf, maxScanTokenSize)

	for scanner.Scan() {
		line := scanner.Text()
		processForkliftLogLine(line, planName)
	}

	if err := scanner.Err(); err != nil && err != io.EOF {
		logPrint("[FORKLIFT] ERROR: Log scanner error: %v\n", err)
	}

	cmd.Wait()
}

func processForkliftLogLine(line, planName string) {
	var entry ForkliftLogEntry
	if err := json.Unmarshal([]byte(line), &entry); err != nil {
		// Not JSON, skip
		return
	}

	// Filter by plan name if specified
	if planName != "" {
		if planField, ok := entry.Fields["plan"].(map[string]interface{}); ok {
			if name, ok := planField["name"].(string); !ok || name != planName {
				return
			}
		} else {
			return // No plan field, skip
		}
	}

	// Parse timestamp
	ts, err := time.Parse("2006-01-02 15:04:05.999", entry.Ts)
	if err != nil {
		// Try without milliseconds
		ts, err = time.Parse("2006-01-02 15:04:05", entry.Ts)
		if err != nil {
			ts = time.Now()
		}
	}
	timestamp := ts.Format("15:04:05.000")

	// Filter for important events
	important := false
	var message string

	switch entry.Msg {
	case "Phase", "VM state changed", "VM phase changed":
		if phase, ok := entry.Fields["phase"].(string); ok {
			message = fmt.Sprintf("🔄 Phase: %s", phase)
			important = true
		}
	case "SetCheckpoint":
		if current, ok := entry.Fields["current"].(string); ok {
			message = fmt.Sprintf("📸 SetCheckpoint: current=%s", current)
			important = true
			if previous, ok := entry.Fields["previous"].(string); ok && previous != "" {
				message += fmt.Sprintf(" previous=%s", previous)
			}
			if entry.Logger != "" {
				message += fmt.Sprintf(" [%s]", entry.Logger)
			}
		}
	case "CreateSnapshot":
		message = "📸 CreateSnapshot"
		if entry.Logger != "" {
			message += fmt.Sprintf(" [%s]", entry.Logger)
		}
		important = true
	case "RemoveSnapshot", "Removing snapshot":
		if snapshot, ok := entry.Fields["snapshot"].(string); ok {
			message = fmt.Sprintf("🗑️  RemoveSnapshot: %s", snapshot)
		} else {
			message = "🗑️  RemoveSnapshot"
		}
		// Add logger context to distinguish duplicates
		if entry.Logger != "" {
			message += fmt.Sprintf(" [%s]", entry.Logger)
		}
		important = true
	case "Precopy", "Starting precopy", "Precopy complete":
		message = fmt.Sprintf("📦 %s", entry.Msg)
		important = true
	case "Cutover", "Starting cutover":
		message = "✂️  Cutover initiated"
		important = true
	case "Power off", "Power on":
		message = fmt.Sprintf("⚡ %s VM", entry.Msg)
		important = true
	case "Snapshot already exists in DataVolume checkpoints list":
		message = "⚠️  Duplicate checkpoint detected"
		important = true
	}

	if important {
		vmName := ""
		if vmRef, ok := entry.Fields["vmRef"].(map[string]interface{}); ok {
			if name, ok := vmRef["name"].(string); ok {
				vmName = name
			}
		}
		if vmName != "" {
			logPrint("[%s] [FORKLIFT:%s] %s\n", timestamp, vmName, message)
		} else {
			logPrint("[%s] [FORKLIFT] %s\n", timestamp, message)
		}
	}
}
